### ISSUE TITLE
Unable to Sign Out Using the "Sign Out" Button

### ISSUE THREAD

**Issue by KujanL** [genome/civic-server#106] opened 2015-11-11 22:21 UTC
The cursor changes when you move over the button, however when you click on the "Sign Out" Button nothing happens.

![screen shot 2015-11-11 at 9 31 04 am](https://cloud.githubusercontent.com/assets/15361912/11104751/2a392c8e-8890-11e5-92e8-994343b9e801.png)

**Comment by kkrysiak** [comment] 2015-11-11 23:13
If you refresh the page, it does actually sign you out. 

This is related to the client-side issue https://github.com/genome/civic-client/issues/265

**Comment by acoffman** [comment] 2015-11-25 19:38
Yeah, this is a duplicate of https://github.com/genome/civic-client/issues/265

Going to go ahead and close it so we only have one copy of the issue, but thanks for the report!

**Closed by acoffman** 2015-11-25 19:38 UTC
