### ISSUE TITLE
Problem with CIViC_Bot hgvs generation

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#315] opened 2017-05-14 00:23 UTC
I haven't noticed it elsewhere yet but since these are automatically generated I worry there is error in the logic. Check out: https://civic.genome.wustl.edu/events/genes/42/summary/variants/113/talk/revisions/list/3908/summary#variant

Note the HGVS string proposed is: "NC_000010.100:g.43617416T>C". The accession version should be ".10" not ".100".

**Comment by acoffman** [comment] 2017-05-17 22:24
This appears to be a duplicate of #297. If the proposed solution there of removing still-pending civic bot suggestions and re-generating them with the typo fixed is acceptable, I'll go ahead and do it; it should be very straightforward! I just wanted an "okay" to go ahead since we generally don't delete things.

**Closed by acoffman** 2017-05-17 22:24 UTC
