### ISSUE TITLE
Add HGVS

### ISSUE THREAD

**Issue by nspies13** [genome/civic-server#28] opened 2015-02-24 23:27 UTC
And by HGVS I mean use chr:start-stop (ref -> var)

**Comment by kkrysiak** [comment] 2015-03-02 00:56
Resolved for SNVs in DoCM. Still need to figure out other variants (fusions, exon level, amplifications). Add N/A for expression changes.

**Comment by malachig** [comment] 2015-04-15 20:52
In our latest meeting we decided that a *single* representative coordinate should be added at the *variant* level instead of the evidence item level.  This would include: build, chr, start, stop, ref, var, representative transcript, chr2, start2, stop2.

**Comment by acoffman** [comment] 2016-09-08 20:03
Closing as duplicate of #143

**Closed by acoffman** 2016-09-08 20:03 UTC
