### ISSUE TITLE
Create a browse sources/publication view that also acts as a curation queue

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#46] opened 2015-03-18 20:41 UTC
It would be great to a have a view in the interface that showed the current 'bibliography' of CIViC.  This would be the list of sources we have obtained 1 to n evidence statements from.  

Use cases:
- We give credit to the authors of papers, while also giving a sense of the number and diversity of papers CIViC leans on.
- User can see if their favorite paper is already in CIViC
- User can add a paper to the queue that they believe has value but hasn't been curated yet.

View could show:
- Compact citation pulled from PubMed as we display elsewhere
- Number of evidence statements pulled from the paper so far
- Status (Curated, pending, etc.)

This view could be a third view:
'Browse by Variant', 'Browse by Gene', and now 'Browse by Source'.

**Comment by acoffman** [comment] 2016-08-15 15:50
Closing as duplicate of the newer genome/civic-client#491

**Closed by acoffman** 2016-08-15 15:50 UTC
Labels: enhancement
